# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='experiences'))),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
