# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='experiences'))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='ORMSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.ORMExperience')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson')),
            ],
            options={
                'verbose_name': 'Save',
                'verbose_name_plural': 'Saves',
            },
        ),
    ]
