# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_ormconfirmationtoken'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ormexperience',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson'),
        ),
    ]
