# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-26 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_ormconfirmationtoken'),
        ('experiences', '0002_ormexperience_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.ORMExperience')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson')),
            ],
            options={
                'verbose_name': 'Save',
                'verbose_name_plural': 'Saves',
            },
        ),
    ]
