# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to=stdimage.utils.UploadToUUID(path='scenes'))),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiences.ORMExperience')),
            ],
            options={
                'verbose_name': 'Scene',
                'verbose_name_plural': 'Scenes',
            },
        ),
    ]
