# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('refresh_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auth token',
                'verbose_name_plural': 'Auth tokens',
            },
        ),
        migrations.CreateModel(
            name='ORMConfirmationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Confirmation token',
                'verbose_name_plural': 'Confirmation tokens',
            },
        ),
        migrations.CreateModel(
            name='ORMPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_email_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='ormconfirmationtoken',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson'),
        ),
        migrations.AddField(
            model_name='ormauthtoken',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ORMPerson'),
        ),
    ]
